export default function refs() {
  return {
    filmsElements: document.querySelectorAll('[data-modal-open]'),
    filmsList: document.querySelector('.all-films-list'),
    // openModalBtn: document.querySelector('[data-modal-open]'),
    closeModalBtn: document.querySelector('[data-modal-close]'),
    modal: document.querySelector('[data-modal]'),
    backdrop: document.querySelector('.backdrop'),
    loader: document.querySelector('.loader'),
    form: document.querySelector('.header__search-form'),
    formInput: document.querySelector('.header__search-input'),
    notification: document.querySelector('.header__error-text'),
    pagination: document.querySelector('.pagination'),
    paginationArrowLeft: document.querySelector('.pagination__arrow_left'),
    paginationFirstPageBtn: document.querySelector('.first-item'),
    paginationSecondPageBtn: document.querySelector('.second-item'),
    paginationThirdPageBtn: document.querySelector('.third-item'),
    paginationFourPageBtn: document.querySelector('.fourth-item'),
    paginationMiddlePageBtn: document.querySelector('.pagination__middle-item'),
    paginationSixPageBtn: document.querySelector('.sixth-item'),
    paginationSevenPageBtn: document.querySelector('.seventh-item'),
    paginationEighthPageBtn: document.querySelector('.eighth-item'),
    paginationLastPageBtn: document.querySelector('.last-item'),
    paginationAllItems: document.querySelectorAll('.pagination li'),
    paginationArrowRight: document.querySelector('.pagination__arrow_right'),
    lampadario: document.querySelector('#lampadario'),
    switch: document.querySelector('.switch'),
    body: document.querySelector('body'),
    modalTmp: document.querySelector('.modal .modal-content'),
  };
}
